 PROCEDURE UPDATE_DELIVERY_NOTE_LINE(p_pedido IN NUMBER, p_fechaped IN DATE, p_articodi IN NUMBER, p_referencia IN VARCHAR2,
        p_artidesc IN VARCHAR2, p_ablncant IN VARCHAR2, p_ablncantumb IN VARCHAR2, p_ablncantinc IN VARCHAR2,
        p_formdesc IN VARCHAR2, p_formcodi IN NUMBER, p_ablnprneto IN VARCHAR2, p_ablnprbruto IN VARCHAR2,
        p_ablnprincr IN VARCHAR2, p_ablnprtasa IN VARCHAR2, p_ablnimporte IN VARCHAR2, p_ablnformatocompra IN NUMBER,
        p_ablnfactorconversion IN NUMBER, p_ablnfactorconversionumb IN NUMBER, p_lote IN VARCHAR2, p_comentario IN VARCHAR2,
        p_ablnprbrutocons IN VARCHAR2, p_ablnprbrutousd IN VARCHAR2, p_ablnprbrutoloc IN VARCHAR2, p_ablnprnetocons IN VARCHAR2,
        p_ablnprincrcons IN VARCHAR2, p_ablnprtasacons IN VARCHAR2, p_ablnimportecons IN VARCHAR2, p_ablnprnetousd IN VARCHAR2,
        p_ablnprincrusd IN VARCHAR2, p_ablnprtasausd IN VARCHAR2, p_ablnimporteusd IN VARCHAR2, p_ablnprnetoloc IN VARCHAR2,
        p_ablnprincrloc IN VARCHAR2, p_ablnprtasaloc IN VARCHAR2, p_ablnimporteloc IN VARCHAR2, p_ablnporcdto IN VARCHAR2,
        p_ablnporcdto1 IN VARCHAR2, p_ablnporcdto2 IN VARCHAR2, p_ablnporcdto3 IN VARCHAR2, p_albacodi IN NUMBER,
        p_centcodi IN VARCHAR2, p_pelnnum IN NUMBER, p_indice IN NUMBER, p_sbalvirtual IN VARCHAR2,
        p_ablnudsgratuitas IN VARCHAR2, p_acucgratudsgrat IN NUMBER, p_acucgratudscomp IN NUMBER, p_ablnprpromo IN NUMBER,
        p_ablnfechacad IN DATE, p_ablnvalidada IN NUMBER DEFAULT 1, p_acuepref IN NUMBER, p_ablncantpend IN VARCHAR2)
    AS
        v_ABLNPRNETO number;
        v_ABLNIMPORTE number;
        v_ABLNPRBRUTO number;
        pconfvalue NUMBER;
        pconfdesc VARCHAR2(100);

        v_ABLNPRBRUTOCONS number;
        v_ABLNPRBRUTOUSD number;
        v_ABLNPRBRUTOLOC number;
        v_ABLNPRNETOCONS number;
        v_ABLNIMPORTECONS number;
        v_ABLNPRNETOUSD number;
        v_ABLNIMPORTEUSD number;
        v_ABLNPRNETOLOC number;
        v_ABLNIMPORTELOC number;

        v_ABLNPORCDTO number;
        v_ABLNPORCDTO1 number;
        v_ablnporcdto2 number;
        v_ABLNPORCDTO3 number;

        v_ABLNPRINCR number;
        v_ABLNPRTASA number;
        v_ABLNPRINCRCONS number;
        v_ABLNPRTASACONS number;
        v_ABLNPRINCRUSD number;
        v_ABLNPRTASAUSD number;
        v_ABLNPRINCRLOC number;
        v_ABLNPRTASALOC number;
        v_monecodicent number;

        v_ABLNCANT number;
        v_ABLNCANTUMB number;
        v_ABLNCANTINC number;
        v_ABLNUDSGRATUITAS number;
        v_ABLNUDSGRATUITASUMB number;

        v_ABLNPRBRUTOUMB number;
        v_ABLNPRNETOUMB number;
        v_ABLNFACTORCONVERSIONUMB number;
        v_formcodi number;
        v_centprecision number;
        V_USERID NUMBER;
    BEGIN
        select formcodi into v_formcodi from cpr05.sac_articulos where articodi = p_articodi;
        select centprecision into v_centprecision from cpr05.centros where centcodi = p_centcodi;

        V_ABLNIMPORTE :=ROUND_IMP(TO_NUMBER(P_ABLNIMPORTE),V_CENTPRECISION);
        V_ABLNPRNETO := ROUND_PRC(TO_NUMBER(P_ABLNPRNETO));
        V_ABLNPRBRUTO := ROUND_PRC(TO_NUMBER(P_ABLNPRBRUTO));        
        V_ABLNPRBRUTOCONS := ROUND_PRC(TO_NUMBER(P_ABLNPRBRUTOCONS));
        V_ABLNPRBRUTOUSD := ROUND_PRC(TO_NUMBER(P_ABLNPRBRUTOUSD));
        V_ABLNPRBRUTOLOC := ROUND_PRC(TO_NUMBER(P_ABLNPRBRUTOLOC));
        V_ABLNPRNETOCONS := ROUND_PRC(TO_NUMBER(P_ABLNPRNETOCONS));
        V_ABLNIMPORTECONS := ROUND_IMP(TO_NUMBER(P_ABLNIMPORTECONS));
        V_ABLNPRNETOUSD :=  ROUND_PRC(TO_NUMBER(P_ABLNPRNETOUSD));
        V_ABLNIMPORTEUSD := ROUND_IMP(TO_NUMBER(P_ABLNIMPORTEUSD));
        V_ABLNPRNETOLOC :=  ROUND_PRC(TO_NUMBER(P_ABLNPRNETOLOC));
        V_ABLNIMPORTELOC := ROUND_IMP(TO_NUMBER(P_ABLNIMPORTELOC),V_CENTPRECISION);

        v_ABLNPORCDTO :=  ROUND_IMP(to_number(p_ABLNPORCDTO,'999999999999999.99999'));
        v_ABLNPORCDTO1 := ROUND_IMP(to_number(p_ABLNPORCDTO1,'999999999999999.99999'));
        v_ABLNPORCDTO2 := ROUND_IMP(to_number(p_ABLNPORCDTO2,'999999999999999.99999'));
        v_ABLNPORCDTO3 := ROUND_IMP(to_number(p_ABLNPORCDTO3,'999999999999999.99999'));

        v_ABLNPRINCR := ROUND_IMP(to_number(p_ABLNPRINCR,'999999999999999.99999'),v_centprecision);
        v_ABLNPRTASA := ROUND_IMP(to_number(p_ABLNPRTASA,'999999999999999.99999'),v_centprecision);
        v_ABLNPRINCRCONS:= ROUND_IMP(to_number(p_ABLNPRINCRCONS,'999999999999999.99999'));
        v_ABLNPRTASACONS := ROUND_IMP(to_number(p_ABLNPRTASACONS,'999999999999999.99999'));
        v_ABLNPRINCRUSD := ROUND_IMP(to_number(p_ABLNPRINCRUSD,'999999999999999.99999'));
        v_ABLNPRTASAUSD := ROUND_IMP(to_number(p_ABLNPRTASAUSD,'999999999999999.99999'));
        v_ABLNPRINCRLOC := ROUND_IMP(to_number(p_ABLNPRINCRLOC,'999999999999999.99999'),v_centprecision);
        v_ABLNPRTASALOC := ROUND_IMP(to_number(p_ABLNPRTASALOC,'999999999999999.99999'),v_centprecision);

        v_ABLNCANT := ROUND_CNT(to_number(p_ABLNCANT,'999999999999999.99999'));
        v_ABLNCANTUMB := ROUND_CNT(to_number(p_ABLNCANTUMB,'999999999999999.99999'));
        v_ABLNCANTINC := ROUND_CNT(to_number(p_ABLNCANTINC,'999999999999999.99999'));
        v_ABLNUDSGRATUITAS := 0; --ROUND_CNT(to_number(p_ABLNUDSGRATUITAS,'999999999999999.99999'));

        --Conversiones a UMB
        v_ABLNPRBRUTOUMB :=ROUND_PRC(CPR05.PCK_LOCALE.UNMLOCALTOBASEPRC(p_CENTCODI, v_formcodi, v_ABLNPRBRUTO));
        v_ABLNPRNETOUMB  :=ROUND_PRC(CPR05.PCK_LOCALE.UNMLOCALTOBASEPRC(p_CENTCODI, v_formcodi, v_ABLNPRNETO));
        v_ABLNFACTORCONVERSIONUMB  := ROUND_TC(CPR05.PCK_LOCALE.UNMLOCALTOBASECNT(p_CENTCODI, v_formcodi, p_ABLNFACTORCONVERSION));
        v_ABLNPRBRUTOLOC :=ROUND_PRC(CPR05.PCK_LOCALE.UNMLOCALTOBASEPRC(p_CENTCODI, v_formcodi, v_ABLNPRBRUTOLOC));
        v_ABLNPRNETOLOC  :=ROUND_PRC(CPR05.PCK_LOCALE.UNMLOCALTOBASEPRC(p_CENTCODI, v_formcodi, v_ABLNPRNETOLOC));
        v_ABLNPRBRUTOCONS :=ROUND_PRC(CPR05.PCK_LOCALE.UNMLOCALTOBASEPRC(p_CENTCODI, v_formcodi, v_ABLNPRBRUTOCONS));
        v_ABLNPRNETOCONS  :=ROUND_PRC(CPR05.PCK_LOCALE.UNMLOCALTOBASEPRC(p_CENTCODI, v_formcodi, v_ABLNPRNETOCONS));
        v_ABLNPRBRUTOUSD :=ROUND_PRC(CPR05.PCK_LOCALE.UNMLOCALTOBASEPRC(p_CENTCODI, v_formcodi, v_ABLNPRBRUTOUSD));
        v_ABLNPRNETOUSD  :=ROUND_PRC(CPR05.PCK_LOCALE.UNMLOCALTOBASEPRC(p_CENTCODI, v_formcodi, v_ABLNPRNETOUSD));
        v_ABLNUDSGRATUITASUMB := ROUND_CNT(CPR05.PCK_LOCALE.UNMLOCALTOBASECNT(p_CENTCODI, v_formcodi, v_ABLNUDSGRATUITAS));

        SELECT COUNT(1) INTO pconfvalue FROM ALBARANESLINEAS WHERE CENTCODI = p_CENTCODI AND ALBACODI = p_ALBACODI;

        pconfvalue := pconfvalue + 1;
        pconfvalue := pconfvalue + 1;       

        INSERT INTO ALBARANESLINEAS
            (CENTCODI, ALBACODI, ABLNNUM, ARTICODI, PEDICODI,
            ABLNCANT, ABLNCANTUMB, ABLNCANTINC, ABLNPRBRUTO, ABLNPORCDTO,
            ABLNPORCDTO1, ABLNPORCDTO2, ABLNPORCDTO3, ABLNPRNETO, ABLNPRINCR,
            ABLNPRTASA, ABLNIMPORTE, ABLNFORMATOCOMPRA, ABLNFACTORCONVERSION, ABLNFACTORCONVERSIONUMB,
            ACUEREFPROV, ABLNCOMEN, ABLNPRBRUTOCONS, ABLNPRBRUTOUSD, ABLNPRBRUTOLOC,
            ABLNPRNETOCONS, ABLNPRNETOUSD, ABLNPRNETOLOC, ABLNPRINCRCONS, ABLNPRINCRUSD,
            ABLNPRINCRLOC, ABLNPRTASACONS, ABLNPRTASAUSD, ABLNPRTASALOC, ABLNIMPORTECONS,
            ABLNIMPORTEUSD, ABLNIMPORTELOC, PELNNUM, INDICE, ABLNLOTE,
            ESTACODI, ABLNCANTPEND, ABLNCANTPENDUMB, ABLNPRBRUTOUMB, ABLNPRNETOUMB,
            SBALVIRTUAL, ABLNUDSGRATUITAS, ABLNUDSGRATUITASUMB, ACUCGRATUDSGRAT, ACUCGRATUDSCOMP,
            ABLNPRPROMO, ABLNFECHACAD, ABLNVALIDADA, ACUEPREF)
        VALUES
            (p_CENTCODI, p_ALBACODI, pconfvalue, p_ARTICODI, p_PEDIDO,
            v_ABLNCANT, CPR05.PCK_LOCALE.UNMLOCALTOBASECNT(p_CENTCODI, v_formcodi, v_ABLNCANT),
            v_ABLNCANTINC, v_ABLNPRBRUTO, v_ABLNPORCDTO,
            v_ABLNPORCDTO1, v_ABLNPORCDTO2, v_ABLNPORCDTO3, v_ABLNPRNETO, v_ABLNPRINCR,
            v_ABLNPRTASA, v_ABLNIMPORTE, p_ABLNFORMATOCOMPRA, p_ABLNFACTORCONVERSION, v_ABLNFACTORCONVERSIONUMB,
            p_REFERENCIA, p_COMENTARIO, v_ABLNPRBRUTOCONS, v_ABLNPRBRUTOUSD, v_ABLNPRBRUTOLOC,
            v_ABLNPRNETOCONS, v_ABLNPRNETOUSD, v_ABLNPRNETOLOC, v_ABLNPRINCRCONS, v_ABLNPRINCRUSD,
            v_ABLNPRINCRLOC, v_ABLNPRTASACONS, v_ABLNPRTASAUSD, v_ABLNPRTASALOC, v_ABLNIMPORTECONS,
            v_ABLNIMPORTEUSD, v_ABLNIMPORTELOC, p_PELNNUM, p_INDICE, p_LOTE,
            0, p_ablncantpend, CPR05.PCK_LOCALE.UNMLOCALTOBASECNT(p_CENTCODI, v_formcodi, v_ABLNCANT), v_ABLNPRBRUTOUMB, v_ABLNPRNETOUMB,
            p_SBALVIRTUAL, v_ABLNUDSGRATUITAS, v_ABLNUDSGRATUITASUMB, p_ACUCGRATUDSGRAT, p_ACUCGRATUDSCOMP,
            p_ABLNPRPROMO, p_ABLNFECHACAD, NVL(p_ABLNVALIDADA,1), p_ACUEPREF);

    END UPDATE_DELIVERY_NOTE_LINE;